title: Adedeji Ogundipe
logo: DA_img.jpg
description: A data analyst, compliance analyst, and certified accountant with over 3 years experience in data cleansing, validation, manipulation and interrogation, business intelligence, and report automation using advanced excel, SQL, power BI, google sheets, python, and R.  
# Show_downloads: true
# Google_analytics: 
theme: Jekyll-theme-minimal
